### PR TITLE
Auto detect kubernetes cluster

### LINKED ISSUE #1321: GKE upgrade v1.25 to v1.28 broke odigos daemonsets
**Describe the bug**
GKE update from v1.25 pra v1.28 broke odigos daemonsets

I am getting the following error:
`Warning  FailedCreate  2m5s (x85 over 8h)  daemonset-controller  Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]
`
Another problem is that, after update, due to the daemonsets not starting, the apps orchestrated by Odigos also did not start.

**To Reproduce**
Update GKE from v1.25 to v1.28

### PR DESCRIPTION
**Pull request by edeNFed**
Closes #1321

### CODE REVIEW

File: cli/cmd/resources/odiglet.go [hunk 1]
```diff
@@ -362,6 +366,33 @@ func NewSCClusterRoleBinding(ns string) *rbacv1.ClusterRoleBinding {
 	}
 }
 
+func NewRResourceQuota(ns string) *corev1.ResourceQuota {
```
Comment (blumamir) [inline cli/cmd/resources/odiglet.go:369]:
```suggestion
func NewResourceQuota(ns string) *corev1.ResourceQuota {
```

**Review by blumamir — APPROVED** [review]
